#
# HTTP

http:
  host: "localhost"
  port: "8081"

#
# ActiveMQ
jms:
  user: "admin"
  password: "admin"
  broker:
    host: "localhost"
    port: "61616"
  queue: 
    name: "uc-jms-transaction"
  queuePolicy: 
    initialRedeliveryDelay: "1000"
    redeliveryDelay: "1000"
    maximumRedeliveries: "3"
  ttl: "5"
test:
  redeliveriesAttempts: "5"